### ISSUE TITLE
笔试题一反馈

### ISSUE THREAD

**Issue by zhugw** [prclin/interview#1]
1. csv中的 json有2种格式  实际解析出来应该有67个storeName

```
              result.data[].data.storeId
              result.data[].data.storeName
             
              result.data[].data.resources.storeId
              result.data[].data.resources.storeName
```

2. 打标签也不符合需求呢
storeName需要包含 关键词1 and 包含关键词2 and 包含关键词3 才算命中 且只能匹配一个
如 `大润发(东升店)` 匹配不上 但是你的代码对应的tag却有这么多
```
大润发（深南路店） 大润发（建设路店） 大润发（孝感店） 大润发（九江店） 大润发（南亭公路店） 大润发（哈尔滨松北店） 大润发（台州黄岩店） 大润发（哈尔滨南岗店） 大润发（上海南路店） 大润发荣昌店 大润发（郁洲北路店） 大润发（邗江路店） 大润发（塘桥南京路店） 大润发（繁兴路店） 大润发（红旗路店） 大润发（秀沿路店） 大润发（吉林西山店） 西宁大润发（文汇路店） 大润发（铜锣湾广场店） 大润发（丽华北路店） 大润发（葫芦岛龙湾大街店） 大润发（龙游店） 大润发（浏阳店） 大润发（芙蓉店） 大润发（吉林解放北路店） 大润发（友谊路店） 大润发（无锡盛岸西路店） 大润发（东欣大道店） 大润发（中环东路店） 大润发（常熟将军路店） 大润发（中山西路店） 大润发（相山北路店） 大润发（历城店） 大润发（金科路店） 大润发（丹东锦山大街店） 大润发（莱州店） 大润发（涂山东路店） 大润发（丹阳吾悦广场店） 大润发峨眉山店 大润发（辽阳新运大街店） 大润发（莱阳店） 大润发（句容华阳东路店） 大润发（兴化武南路店） 大润发（文昌路店） 大润发（当涂店） 大润发（吴江舜新中路店） 大润发（人民路店） 大润发（博物馆路店） 大润发（淮安公园店） 大润发（鹿城店） 大润发（济宁店） 大润发（株洲红旗路店） 大润发（合肥望江东路店） 大润发RTMart（中山西路店） 大润发（佳木斯向阳店） 大润发（烟台店） 大润发（滕州店） 大润发（宣城广德县店） 大润发（青州店） 大润发（开发东路店） 大润发（北安店） 大润发（鞍山民生店） 大润发（胜利东路店） 大润发（侨乡店） 大润发（世昌店） 大润发（宁国宁阳路店） 银川大润发（新华联店） 大润发（东川路店） 大润发（向阳西路店） 大润发（紫御府店） 大润发（泰南路店） 大润发（新浦路店） 大润发（淮南国庆中路店） 大润发（博乐路店） 大润发（杭州建德店） 大润发（盘锦渤海路店） 大润发（迎宾路余之城生活广场店） 大润发（兴义商城店） 大润发（沈阳迎春街店） 大润发（台州南路店） 大润发（九百购物中心店） 大润发（独秀大道店） 大润发镇江（扬子江路店） 大润发（人民中路店） 大润发（清溪路店） 大润发（江阴普惠北路店） 大润发（雨花区奎塘店） 大润发（大庆萨尔图店） 大润发（苏州广济南路店） 大润发（佳木斯万新店） 大润发（七台河店） 大润发（中原路店） 大润发（铜陵石城大道店） 大润发（无锡锡沪路店） 大润发（黄海中路店） 大润发（苏州星塘街店） 大润发（丰乐北路店） 大润发（雨山东路店） 大润发镇江（小米山路店） 大润发（沈阳文艺路店） 大润发（营口朝阳路店） 大润发（天门店） 大润发（宁波象山店） 大润发（东昌店） 大润发（齐齐哈尔建华店） 大润发（黄山店） 大润发（路劲又一城店） 大润发（灵秀中路店） 大润发（迎宾路店） 大润发（曹县店） 大润发（木渎中山东路店） 大润发（蒙山店） 大润发（衢州店） 大润发（芜湖繁昌店） 大润发（张家港东二环路店） 大润发（平度店） 大润发（江汉店） 大润发（济源济水店） 大润发超市（雁滩路店） 大润发（岳阳店） 大润发（安宁连然街店） 大润发（八一店） 大润发（吉林船营店） 大润发（淮北相山路店） 大润发（大关路店） 大润发（郭庄路店） 大润发（红兰中路店） 大润发（紫云路店） 大润发（淮阴店） 大润发（世纪商业中心店） 大润发合川店 大润发（玉环双港路店） 大润发（烟台欧尚店） 大润发（章丘店） 大润发（应天大街店） 大润发（雨山店） 大润发（瑞安塘下店） 大润发（常熟黄河路店） 大润发（环城南路店） 大润发（洪泽湖路店） 大润发（淮安洪泽店） 大润发（宿州葛园三巷店） 大润发（苏州何山店） 大润发（常州关河东路店） 大润发（解放南路店） 大润发（中南大有境店） 大润发（东吴南路店） 大润发（通海路店） 大润发（文昌中路店） 大润发RTMart（凤溪大道店） 大润发（鞍山解放东路店） 大润发（南环路店） 大润发（怀化店） 大润发南部店 大润发（花津南店） 大润发（金港黄泗浦西路店） 大润发（宁波北仑店） 大润发（怀远店） 大润发（常州勤业路店） 大润发（草场门大街店） 大润发（锦州古塔店） 大润发（绿地大融城店） 大润发（常熟琴湖路店） 大润发（东风路店） 大润发（云林荟聚购物中心店） 大润发（荆州店） 大润发（国庆东路店） 大润发（合肥翡翠路店） 大润发（涟水店） 大润发（朝阳路店） 大润发（沈阳昆山西路店） 大润发RTMart（施家南路店） 大润发（共和新路店） 大润发（长青路店） 大润发（荆沙店） 大润发（湖西路店） 大润发（北大街店） 大润发（莲塘店） 大润发（徐州煤建路店） 大润发（阜新细河店） 大润发（阜新海州店） 大润发（牡丹江西安路店） 大润发（青山湖店） 大润发（诸暨大唐店） 大润发（姑嫂树店） 大润发（三里河店） 大润发（省博店） 大润发（池州长江路店） 大润发（金华永康店） 大润发（常州今创路店） 大润发（安庆汇峰广场店） 大润发（文登店） 大润发（溧水天生桥大道店） 大润发（金台大道店） 大润发（绍兴诸暨店） 大润发（昆山前进东路店） 大润发（孙权路店） 大润发（吉林白城店） 大润发（桃源中路店） 大润发（苏州金鸡湖店) 大润发（南芦公路店） 大润发（明珠广场店） 大润发正阳店 大润发（海城北关街店） 大润发（北京中路店） 大润发（横港路店） 大润发（秦淮路店） 大润发（旺角城新天地店） 大润发（千灯尚书路店） 大润发（相城齐门北大街店） 大润发（海源路店） 大润发（黄冈店） 大润发（历下店） 大润发（兖州店） 大润发（世贸广场店） 大润发（先锋国际广场店） 大润发（铁岭哈大路店） 大润发（鸠江北路店） 大润发镇江（学府路店） 大润发（双鸭山店） 大润发（官南大道店） 大润发（青年中路店） 大润发（吴江西二环路店） 大润发（张家港沙洲中路店） 大润发（钢城大道店） 大润发（淮安楚州店） 大润发（黄兴路店） 大润发（相城华元路店） 大润发（无锡广瑞路店） 大润发（月罗路店） 大润发（新郁路店） 大润发（西双版纳店） 大润发镇江（中山东路店） 大润发（新桥北路店） 大润发（红旗店） 大润发（滨州店） 大润发（丽水店） 大润发（丹凤街店） 大润发（合肥庐阳店） 大润发（湖北东路店） 大润发（苏州苏福路店） 大润发（超华城市广场店） 大润发璧山店 大润发（苏州长江路店） 大润发（荣成店） 大润发（宣城梅溪路店） 大润发（珠江东路店） 大润发（全福店） 大润发（龙湾店） 大润发（龙蟠中路店） 大润发（吉安店） 大润发（春申路店） 大润发（金港中路店） 大润发（新华路店） 大润发（北城店） 大润发（路桥店） 大润发（鞍山湖南街店） 大润发（哈尔滨道外店） 大润发（蒙山北路店） 大润发蓝光店 大润发（长春19店） 大润发（大庆西宾店） 大润发（中环西路店） 大润发（南通如皋店） 大润发（莱芜店） 大润发（常州永宁北路店） 大润发安徽明光店（池河大道店） 大润发（靖江工农路店） 大润发（苏州宝带西路店） 大润发（沪宜公路店） 大润发（太仓太平南路店） 大润发（宁波奉化店） 大润发（宜昌店） 大润发（太平洋广场店） 大润发（宜兴氿滨南路店） 大润发（齐齐哈尔铁锋店） 大润发（龙盛国际商业广场店） 大润发（沈阳建设西路店） 大润发（黄果树大街店） 大润发（朝阳朝阳大街店） 大润发（百丈东路店） 大润发（城阳店） 大润发（工农大街店） 大润发（牡丹江店） 大润发（苏州浒关文昌路店） 大润发（宁波洪塘店） 大润发（常德洞庭大道店） 大润发（五湖店） 大润发（滨河路店） 大润发（澄浏中路店） 大润发（常州九州新世界广场店） 大润发（宁波慈溪店） 大润发（桐庐店） 大润发（共和新路2008号店） 大润发（衢州江山店） 大润发（锦州体育场店） 大润发（人民西路店） 大润发（昆山朝阳中路店） 大润发（扬州竹西路店） 大润发（袍江开发区店） 大润发（大唐西市店） 大润发（阜阳临泉店） 大润发（银湖中路店） 大润发（淄博店） 大润发（温州瑞安店） 大润发（松原店） 大润发（太和店） 大润发（怀德中路店） 大润发（欧尚蔡甸店） 大润发（温州龙港店） 大润发（东湖南路店） 大润发眉山店 大润发（市民大道店） 大润发（天心店） 大润发（乌江路店） 大润发（继光大道店） 大润发（淮安花漾城店） 大润发（章江店） 大润发（吴江中山南路店） 大润发（台州东海店） 大润发（泗州中大街店） 大润发（石桥路店） 大润发（溧阳燕山中路店） 大润发（宜兴阳羡东路店） 大润发（抚州店） 大润发（幸福东大街店） 大润发（无锡青祁路店） 大润发（江阴延陵路店） 大润发（泰安店） 大润发（荣乐中路店） 大润发（随州店） 大润发（无锡蠡湖大道店） 大润发（嘉亭荟城市生活广场店） 大润发（吉林东市店） 大润发生活超市（保利广场店） 大润发（宁乡店） 大润发（赣州店） 大润发（欣欣路店） 大润发（通辽店） 大润发德阳店 大润发（俞泾港路店） 大润发（绥化店） 大润发（胶州店） 大润发（汉中门大街店） 大润发（日照店） 大润发（阜阳颍河西路店） 大润发（长城店） 大润发（苏州东环路店） 大润发（青岛店） 大润发（金寨南路店） 大润发（昆明金源大道店） 大润发（烟台福海路店） 大润发（吴江笠泽路店） 大润发（齐齐哈尔龙沙店） 大润发（中钰购物中心店） 大润发（经一路店） 大润发（上饶凤凰店） 大润发（鞍山立山店） 大润发（长江北路店） 大润发（沈阳长白店） 大润发（任港路店） 大润发（营口东升路店） 大润发（慈溪三北中路店） 大润发宜宾店 大润发（吉林辽源店） 大润发（常州兰陵路店） 大润发（泰州梅兰东路店） 大润发（崂山店） 大润发（哈尔滨香坊店） 大润发（池州青阳店） 大润发（市中店） 大润发（天桥店） 大润发（三水新都会店） 大润发（盘锦泰山北路店） 大润发绵阳店 大润发（黄河路店） 大润发（即墨店） 大润发（无锡凤宾路店） 大润发（长阳路店） 大润发（沈阳南京南街店） 大润发（枣庄店） 大润发（商丘归德时代购物中心店） 
```

3. 词典排序的逻辑 没有呢
<img width="739" alt="image" src="https://github.com/prclin/interview/assets/4953871/bafebf3e-614f-48c5-b981-039862a2ce8f">

像这种只有一个关键词的得放在最后 否则后面的都匹配不上了 都匹配这个了

**Comment by prclin** [comment]
1.
 一个data字段过大，没有注意到，不好意思

2.
4.词典排序 按照关键词多的排在前面 如先匹配3个关键词都有的 再匹配2个关键词都有的 最后匹配只有1个的
不好意思理解错了，我以为是对storeName的关键词命中数量的排序，依次命中3个，2个，1个排序

马上改正

**Comment by prclin** [comment]
1.解决多态序列化，实际得到73条（不知道是否有错）
![image](https://github.com/prclin/interview/assets/78372151/035fc248-37c0-4a93-abc0-662284bd0b7f)
2.解决重复标签与标签匹配
```java
private List<TagTreeNode> readTagLibrary() throws IOException {

        List<TagTreeNode> tagTree = new LinkedList<>();
        String filePath = new ClassPathResource("/static/标签词库1026.xlsx").getFile().getAbsolutePath();
        EasyExcel.read(filePath, Tag.class, new PageReadListener<Tag>(dataList -> {
            for (Tag tag : dataList) {
                List<TagTreeNode> children = insertNode(tagTree, new TagTreeNode(tag.getKey1(), tag.getName())).getChildren();
                List<TagTreeNode> children1 = insertNode(children, new TagTreeNode(tag.getKey2(), tag.getName())).getChildren();
                insertNode(children1, new TagTreeNode(tag.getKey3(), tag.getName()));
            }
        })).sheet().doRead();
        return tagTree;
    }
```
commit id 232be2970e30bba1b814c3af835ec7e82211f0f5

**Comment by prclin** [comment]
> 1. csv中的 json有2种格式  实际解析出来应该有67个storeName
> 
> ```
>               result.data[].data.storeId
>               result.data[].data.storeName
>              
>               result.data[].data.resources.storeId
>               result.data[].data.resources.storeName
> ```
> 
> 2. 打标签也不符合需求呢
>    storeName需要包含 关键词1 and 包含关键词2 and 包含关键词3 才算命中 且只能匹配一个
>    如 `大润发(东升店)` 匹配不上 但是你的代码对应的tag却有这么多
> 
> ```
> 大润发（深南路店） 大润发（建设路店） 大润发（孝感店） 大润发（九江店） 大润发（南亭公路店） 大润发（哈尔滨松北店） 大润发（台州黄岩店） 大润发（哈尔滨南岗店） 大润发（上海南路店） 大润发荣昌店 大润发（郁洲北路店） 大润发（邗江路店） 大润发（塘桥南京路店） 大润发（繁兴路店） 大润发（红旗路店） 大润发（秀沿路店） 大润发（吉林西山店） 西宁大润发（文汇路店） 大润发（铜锣湾广场店） 大润发（丽华北路店） 大润发（葫芦岛龙湾大街店） 大润发（龙游店） 大润发（浏阳店） 大润发（芙蓉店） 大润发（吉林解放北路店） 大润发（友谊路店） 大润发（无锡盛岸西路店） 大润发（东欣大道店） 大润发（中环东路店） 大润发（常熟将军路店） 大润发（中山西路店） 大润发（相山北路店） 大润发（历城店） 大润发（金科路店） 大润发（丹东锦山大街店） 大润发（莱州店） 大润发（涂山东路店） 大润发（丹阳吾悦广场店） 大润发峨眉山店 大润发（辽阳新运大街店） 大润发（莱阳店） 大润发（句容华阳东路店） 大润发（兴化武南路店） 大润发（文昌路店） 大润发（当涂店） 大润发（吴江舜新中路店） 大润发（人民路店） 大润发（博物馆路店） 大润发（淮安公园店） 大润发（鹿城店） 大润发（济宁店） 大润发（株洲红旗路店） 大润发（合肥望江东路店） 大润发RTMart（中山西路店） 大润发（佳木斯向阳店） 大润发（烟台店） 大润发（滕州店） 大润发（宣城广德县店） 大润发（青州店） 大润发（开发东路店） 大润发（北安店） 大润发（鞍山民生店） 大润发（胜利东路店） 大润发（侨乡店） 大润发（世昌店） 大润发（宁国宁阳路店） 银川大润发（新华联店） 大润发（东川路店） 大润发（向阳西路店） 大润发（紫御府店） 大润发（泰南路店） 大润发（新浦路店） 大润发（淮南国庆中路店） 大润发（博乐路店） 大润发（杭州建德店） 大润发（盘锦渤海路店） 大润发（迎宾路余之城生活广场店） 大润发（兴义商城店） 大润发（沈阳迎春街店） 大润发（台州南路店） 大润发（九百购物中心店） 大润发（独秀大道店） 大润发镇江（扬子江路店） 大润发（人民中路店） 大润发（清溪路店） 大润发（江阴普惠北路店） 大润发（雨花区奎塘店） 大润发（大庆萨尔图店） 大润发（苏州广济南路店） 大润发（佳木斯万新店） 大润发（七台河店） 大润发（中原路店） 大润发（铜陵石城大道店） 大润发（无锡锡沪路店） 大润发（黄海中路店） 大润发（苏州星塘街店） 大润发（丰乐北路店） 大润发（雨山东路店） 大润发镇江（小米山路店） 大润发（沈阳文艺路店） 大润发（营口朝阳路店） 大润发（天门店） 大润发（宁波象山店） 大润发（东昌店） 大润发（齐齐哈尔建华店） 大润发（黄山店） 大润发（路劲又一城店） 大润发（灵秀中路店） 大润发（迎宾路店） 大润发（曹县店） 大润发（木渎中山东路店） 大润发（蒙山店） 大润发（衢州店） 大润发（芜湖繁昌店） 大润发（张家港东二环路店） 大润发（平度店） 大润发（江汉店） 大润发（济源济水店） 大润发超市（雁滩路店） 大润发（岳阳店） 大润发（安宁连然街店） 大润发（八一店） 大润发（吉林船营店） 大润发（淮北相山路店） 大润发（大关路店） 大润发（郭庄路店） 大润发（红兰中路店） 大润发（紫云路店） 大润发（淮阴店） 大润发（世纪商业中心店） 大润发合川店 大润发（玉环双港路店） 大润发（烟台欧尚店） 大润发（章丘店） 大润发（应天大街店） 大润发（雨山店） 大润发（瑞安塘下店） 大润发（常熟黄河路店） 大润发（环城南路店） 大润发（洪泽湖路店） 大润发（淮安洪泽店） 大润发（宿州葛园三巷店） 大润发（苏州何山店） 大润发（常州关河东路店） 大润发（解放南路店） 大润发（中南大有境店） 大润发（东吴南路店） 大润发（通海路店） 大润发（文昌中路店） 大润发RTMart（凤溪大道店） 大润发（鞍山解放东路店） 大润发（南环路店） 大润发（怀化店） 大润发南部店 大润发（花津南店） 大润发（金港黄泗浦西路店） 大润发（宁波北仑店） 大润发（怀远店） 大润发（常州勤业路店） 大润发（草场门大街店） 大润发（锦州古塔店） 大润发（绿地大融城店） 大润发（常熟琴湖路店） 大润发（东风路店） 大润发（云林荟聚购物中心店） 大润发（荆州店） 大润发（国庆东路店） 大润发（合肥翡翠路店） 大润发（涟水店） 大润发（朝阳路店） 大润发（沈阳昆山西路店） 大润发RTMart（施家南路店） 大润发（共和新路店） 大润发（长青路店） 大润发（荆沙店） 大润发（湖西路店） 大润发（北大街店） 大润发（莲塘店） 大润发（徐州煤建路店） 大润发（阜新细河店） 大润发（阜新海州店） 大润发（牡丹江西安路店） 大润发（青山湖店） 大润发（诸暨大唐店） 大润发（姑嫂树店） 大润发（三里河店） 大润发（省博店） 大润发（池州长江路店） 大润发（金华永康店） 大润发（常州今创路店） 大润发（安庆汇峰广场店） 大润发（文登店） 大润发（溧水天生桥大道店） 大润发（金台大道店） 大润发（绍兴诸暨店） 大润发（昆山前进东路店） 大润发（孙权路店） 大润发（吉林白城店） 大润发（桃源中路店） 大润发（苏州金鸡湖店) 大润发（南芦公路店） 大润发（明珠广场店） 大润发正阳店 大润发（海城北关街店） 大润发（北京中路店） 大润发（横港路店） 大润发（秦淮路店） 大润发（旺角城新天地店） 大润发（千灯尚书路店） 大润发（相城齐门北大街店） 大润发（海源路店） 大润发（黄冈店） 大润发（历下店） 大润发（兖州店） 大润发（世贸广场店） 大润发（先锋国际广场店） 大润发（铁岭哈大路店） 大润发（鸠江北路店） 大润发镇江（学府路店） 大润发（双鸭山店） 大润发（官南大道店） 大润发（青年中路店） 大润发（吴江西二环路店） 大润发（张家港沙洲中路店） 大润发（钢城大道店） 大润发（淮安楚州店） 大润发（黄兴路店） 大润发（相城华元路店） 大润发（无锡广瑞路店） 大润发（月罗路店） 大润发（新郁路店） 大润发（西双版纳店） 大润发镇江（中山东路店） 大润发（新桥北路店） 大润发（红旗店） 大润发（滨州店） 大润发（丽水店） 大润发（丹凤街店） 大润发（合肥庐阳店） 大润发（湖北东路店） 大润发（苏州苏福路店） 大润发（超华城市广场店） 大润发璧山店 大润发（苏州长江路店） 大润发（荣成店） 大润发（宣城梅溪路店） 大润发（珠江东路店） 大润发（全福店） 大润发（龙湾店） 大润发（龙蟠中路店） 大润发（吉安店） 大润发（春申路店） 大润发（金港中路店） 大润发（新华路店） 大润发（北城店） 大润发（路桥店） 大润发（鞍山湖南街店） 大润发（哈尔滨道外店） 大润发（蒙山北路店） 大润发蓝光店 大润发（长春19店） 大润发（大庆西宾店） 大润发（中环西路店） 大润发（南通如皋店） 大润发（莱芜店） 大润发（常州永宁北路店） 大润发安徽明光店（池河大道店） 大润发（靖江工农路店） 大润发（苏州宝带西路店） 大润发（沪宜公路店） 大润发（太仓太平南路店） 大润发（宁波奉化店） 大润发（宜昌店） 大润发（太平洋广场店） 大润发（宜兴氿滨南路店） 大润发（齐齐哈尔铁锋店） 大润发（龙盛国际商业广场店） 大润发（沈阳建设西路店） 大润发（黄果树大街店） 大润发（朝阳朝阳大街店） 大润发（百丈东路店） 大润发（城阳店） 大润发（工农大街店） 大润发（牡丹江店） 大润发（苏州浒关文昌路店） 大润发（宁波洪塘店） 大润发（常德洞庭大道店） 大润发（五湖店） 大润发（滨河路店） 大润发（澄浏中路店） 大润发（常州九州新世界广场店） 大润发（宁波慈溪店） 大润发（桐庐店） 大润发（共和新路2008号店） 大润发（衢州江山店） 大润发（锦州体育场店） 大润发（人民西路店） 大润发（昆山朝阳中路店） 大润发（扬州竹西路店） 大润发（袍江开发区店） 大润发（大唐西市店） 大润发（阜阳临泉店） 大润发（银湖中路店） 大润发（淄博店） 大润发（温州瑞安店） 大润发（松原店） 大润发（太和店） 大润发（怀德中路店） 大润发（欧尚蔡甸店） 大润发（温州龙港店） 大润发（东湖南路店） 大润发眉山店 大润发（市民大道店） 大润发（天心店） 大润发（乌江路店） 大润发（继光大道店） 大润发（淮安花漾城店） 大润发（章江店） 大润发（吴江中山南路店） 大润发（台州东海店） 大润发（泗州中大街店） 大润发（石桥路店） 大润发（溧阳燕山中路店） 大润发（宜兴阳羡东路店） 大润发（抚州店） 大润发（幸福东大街店） 大润发（无锡青祁路店） 大润发（江阴延陵路店） 大润发（泰安店） 大润发（荣乐中路店） 大润发（随州店） 大润发（无锡蠡湖大道店） 大润发（嘉亭荟城市生活广场店） 大润发（吉林东市店） 大润发生活超市（保利广场店） 大润发（宁乡店） 大润发（赣州店） 大润发（欣欣路店） 大润发（通辽店） 大润发德阳店 大润发（俞泾港路店） 大润发（绥化店） 大润发（胶州店） 大润发（汉中门大街店） 大润发（日照店） 大润发（阜阳颍河西路店） 大润发（长城店） 大润发（苏州东环路店） 大润发（青岛店） 大润发（金寨南路店） 大润发（昆明金源大道店） 大润发（烟台福海路店） 大润发（吴江笠泽路店） 大润发（齐齐哈尔龙沙店） 大润发（中钰购物中心店） 大润发（经一路店） 大润发（上饶凤凰店） 大润发（鞍山立山店） 大润发（长江北路店） 大润发（沈阳长白店） 大润发（任港路店） 大润发（营口东升路店） 大润发（慈溪三北中路店） 大润发宜宾店 大润发（吉林辽源店） 大润发（常州兰陵路店） 大润发（泰州梅兰东路店） 大润发（崂山店） 大润发（哈尔滨香坊店） 大润发（池州青阳店） 大润发（市中店） 大润发（天桥店） 大润发（三水新都会店） 大润发（盘锦泰山北路店） 大润发绵阳店 大润发（黄河路店） 大润发（即墨店） 大润发（无锡凤宾路店） 大润发（长阳路店） 大润发（沈阳南京南街店） 大润发（枣庄店） 大润发（商丘归德时代购物中心店） 
> ```
> 
> 3. 词典排序的逻辑 没有呢
> 
> <img alt="image" width="739" src="https://user-images.githubusercontent.com/4953871/280452325-bafebf3e-614f-48c5-b981-039862a2ce8f.png">
> 像这种只有一个关键词的得放在最后 否则后面的都匹配不上了 都匹配这个了

已解决

**Comment by zhugw** [comment]
继续反馈

拉取完代码之后  跑com.bxtdata.interview.interview.InterviewApplicationTests#TestCSV

报错：
```
java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "datums" is null

	at com.bxtdata.interview.interview.InterviewApplicationTests.TestCSV(InterviewApplicationTests.java:101)
```
对代码做了如下修改之后
```
List<BaseDatum> datums = result.getData() == null ? Collections.emptyList() : result.getData();
```
生成的csv却是空的 只有表头

```
head .//target/classes/static/output.csv
task_id,storeId,storeName,tag

```

**Comment by prclin** [comment]
> 继续反馈
> 
> 拉取完代码之后 跑com.bxtdata.interview.interview.InterviewApplicationTests#TestCSV
> 
> 报错：
> 
> ```
> java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "datums" is null
> 
> 	at com.bxtdata.interview.interview.InterviewApplicationTests.TestCSV(InterviewApplicationTests.java:101)
> ```
> 
> 对代码做了如下修改之后
> 
> ```
> List<BaseDatum> datums = result.getData() == null ? Collections.emptyList() : result.getData();
> ```
> 
> 生成的csv却是空的 只有表头
> 
> ```
> head .//target/classes/static/output.csv
> task_id,storeId,storeName,tag
> ```

文件错误，在重命名Data类为Data1时，idea自动搜索同名字符，将sample.csv文件内的所有data也修改为了data1，导致反序列化失败，在测试时我只修改了build目录下编译输出的sample.csv文件，没有修改src目录下的sample.csv，在自己测试时能够通过，提交后sample.csv文件还是有错
已改正
