### ISSUE TITLE
拉取反馈

### ISSUE THREAD

**Issue by zhugw** [prclin/interview#2]
1. 我这边尝试调用接口直接报错
```
localhost:8080/breakPriceUrls?batchNo=2023102801&platform=京东&count=10

Caused by: io.lettuce.core.RedisCommandExecutionException: ERR Error running script (call to f_d7c4557154e7266065efc9eb32e926fb9035eb8a): @user_script:14: @user_script: 14: Wrong number of args calling Redis command From Lua script
	at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:147)
	at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:116)
	at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:120)
```

2. 修改之后 最重要的一个功能点也不满足  即并发拉取的时候 还是能重复拉取啊
3. 其他细节 假设有30分钟内 几千个ID放在redis中 id not in (...) 这么多ID 是否合适 
4. 总之还是设计的有些复杂

**Comment by prclin** [comment]
1. 已修复lua脚本，在测试测试成功后的最后一次改动时没测试
2. 功能问题
并发问题：
针对表，设置状态字段unhandled pending processed
![image](https://github.com/prclin/interview/assets/78372151/629ffde5-a06a-4ff7-bc13-64f801222f60)
拉取时限制拉取state为0的数据（基于事务和select for update），然后设置被拉取的state为1，写入redis set key，返回数据
重复拉取：基于键空间通知，使用另一个有expire的key当做锁和过期标志，过期后将记录已拉去链接id的set key中链接的state设为0,并删除set key；在并发拉取时使用expire key作为锁，使得在expire键过期时操作未处理的连接状态时，不会出现问题
上传：上传后置链接state为2，删除set key中对应id；关于文件类型的错误，文件类型时根据图片base64串的前缀获取的，例如data:image/png;base64,前缀，上传图片时需要将前缀一起上传

**Comment by prclin** [comment]
要在redis配置文件中开启键空间通知
notify-keyspace-events KEA

**Comment by prclin** [comment]
> 1. 我这边尝试调用接口直接报错
> 
> ```
> localhost:8080/breakPriceUrls?batchNo=2023102801&platform=京东&count=10
> 
> Caused by: io.lettuce.core.RedisCommandExecutionException: ERR Error running script (call to f_d7c4557154e7266065efc9eb32e926fb9035eb8a): @user_script:14: @user_script: 14: Wrong number of args calling Redis command From Lua script
> 	at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:147)
> 	at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:116)
> 	at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:120)
> ```
> 
> 2. 修改之后 最重要的一个功能点也不满足  即并发拉取的时候 还是能重复拉取啊
> 3. 其他细节 假设有30分钟内 几千个ID放在redis中 id not in (...) 这么多ID 是否合适
> 4. 总之还是设计的有些复杂
已解决

**Comment by zhugw** [comment]
拉取继续反馈：
拉取还是很复杂 我看不大明白  虽然并发调用没有问题 不知道还是会有重复拉取的情况
如 刚拉取了一批 正在截图 到期了 整个的pulled_id被重置了 这一批是不是还是能被拉取 


不知道能不能想到一些更简单的方案

**Comment by zhugw** [comment]
或者  中间程序重启了 会有什么影响呢

**Comment by zhugw** [comment]
拉取 和 redis监听 两个不同的线程同时进行  有没有可能拉取才放进去 那边就到期了 给删除了

**Comment by prclin** [comment]
> 拉取继续反馈： 拉取还是很复杂 我看不大明白 虽然并发调用没有问题 不知道还是会有重复拉取的情况 如 刚拉取了一批 正在截图 到期了 整个的pulled_id被重置了 这一批是不是还是能被拉取
> 
> 不知道能不能想到一些更简单的方案
如果拉取了一批后，正在截图，到期后，会来取pulled_ids将state重置，然后再删除pulled_ids，还能够被拉取，
同时，应为expired_pulled_ids过期，则其他拉取线程获取不到expired_pulled_ids这把锁，就不能够拉取，等到过期处理完成才能拉取；同样在到期时更新state时只有state为1才重置，上传时只有state为1才成功
![image](https://github.com/prclin/interview/assets/78372151/c799fd70-eab1-4935-bba9-7abdd62bfb70)
![image](https://github.com/prclin/interview/assets/78372151/01bc55f0-2dcb-4fa5-bbac-904ec0362f95)
简单方案暂时没思路





> 或者 中间程序重启了 会有什么影响呢
重启时可能存在键空间通知未处理，会重置所有未处理的破价state
![image](https://github.com/prclin/interview/assets/78372151/566a49c9-f2a7-46a8-9e65-76962fbf7f6a)



> 拉取 和 redis监听 两个不同的线程同时进行 有没有可能拉取才放进去 那边就到期了 给删除了
存在，删除后会将state重置，会导致周期性的重复获取，如刚好在过期时间时拉取，然后又要拉取，暂时没想到更好的解决方法

**Comment by zhugw** [comment]
假设不用redis呢 只用MySQL呢 增加一个拉取时间 pull_time
查询待拉取链接的时候
```
where batch_no = ? and platform_name = ? and (state = 0 or (state = 1 and pull_time < current_time - 30分钟)) order by id limit 10 for update
```


或者 定时任务  将拉取时间超过30分钟的再恢复成0

**Comment by prclin** [comment]
> 假设不用redis呢 只用MySQL呢 增加一个拉取时间 pull_time 查询待拉取链接的时候
> 
> ```
> where batch_no = ? and platform_name = ? and (state = 0 or (state = 1 and pull_time < current_time - 30分钟)) order by id limit 10 for update
> ```
> 
> 或者 定时任务 将拉取时间超过30分钟的再恢复成0

哦哦哦，确实，增加一个字段，就可以免去定时任务的复杂实现，同样也可以避免启停带来的不一致，在数据库层面就可以解决问题，学到了
